---
- name: Install Visual Studio Code
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
  become: no
  tags:
    - vscode
    - editor

- name: Check installed VS Code extensions
  ansible.builtin.command: code --list-extensions
  register: installed_extensions
  changed_when: false
  ignore_errors: true # Ignore if code command fails (e.g., VS Code not fully installed yet)
  become: no
  tags:
    - vscode
    - editor
    - extensions

- name: Install VS Code Extension - C# Dev Kit
  ansible.builtin.command: code --install-extension ms-dotnettools.csdevkit
  when: installed_extensions.stdout.find('ms-dotnettools.csdevkit') == -1
  become: no
  tags:
    - vscode
    - editor
    - extensions
    - dotnet

- name: Install VS Code Extension - ESLint
  ansible.builtin.command: code --install-extension dbaeumer.vscode-eslint
  when: installed_extensions.stdout.find('dbaeumer.vscode-eslint') == -1
  become: no
  tags:
    - vscode
    - editor
    - extensions
    - nodejs
    - react

- name: Install VS Code Extension - Prettier
  ansible.builtin.command: code --install-extension esbenp.prettier-vscode
  when: installed_extensions.stdout.find('esbenp.prettier-vscode') == -1
  become: no
  tags:
    - vscode
    - editor
    - extensions
    - nodejs
    - react

- name: Install VS Code Extension - AWS Toolkit
  ansible.builtin.command: code --install-extension amazonwebservices.aws-toolkit-vscode
  when: installed_extensions.stdout.find('amazonwebservices.aws-toolkit-vscode') == -1
  become: no
  tags:
    - vscode
    - editor
    - extensions
    - aws

# Note: Requires 'code' command in PATH. The homebrew cask usually handles this,
# but might require VS Code to be launched once manually first.
